# Generated by Django 5.2.8 on 2026-01-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_alter_centro_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCamaras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(max_length=20)),
                ('responsable', models.CharField(max_length=200)),
                ('rio_pescado_tiene_incidencias', models.BooleanField(default=False)),
                ('rio_pescado_descripcion', models.TextField(default='No se detectaron incidencias durante el monitoreo')),
                ('collin_tiene_incidencias', models.BooleanField(default=False)),
                ('collin_descripcion', models.TextField(default='No se detectaron incidencias durante el monitoreo')),
                ('lican_tiene_incidencias', models.BooleanField(default=False)),
                ('lican_descripcion', models.TextField(default='No se detectaron incidencias durante el monitoreo')),
                ('trafun_tiene_incidencias', models.BooleanField(default=False)),
                ('trafun_descripcion', models.TextField(default='No se detectaron incidencias durante el monitoreo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporte de Cámaras',
                'verbose_name_plural': 'Reportes de Cámaras',
                'ordering': ['-fecha', '-creado_en'],
                'unique_together': {('fecha', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='ControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('dia', models.CharField(max_length=20)),
                ('responsable', models.CharField(max_length=200)),
                ('modulo', models.CharField(default='Hatchery', max_length=100)),
                ('hora_00_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_00_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_00_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_04_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_04_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_04_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_08_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_08_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_08_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_12_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_12_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_12_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_16_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_16_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_16_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_20_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_20_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hora_20_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('promedio_oxigeno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_diarios', to='incidencias.centro')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
                'unique_together': {('centro', 'fecha', 'modulo')},
            },
        ),
    ]
