# Generated by Django 4.2.26 on 2026-01-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0005_reportecamaras_controldiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecamaras',
            name='collin_descripcion',
            field=models.TextField(default='No se detectaron novedades durante el monitoreo'),
        ),
        migrations.AlterField(
            model_name='reportecamaras',
            name='lican_descripcion',
            field=models.TextField(default='No se detectaron novedades durante el monitoreo'),
        ),
        migrations.AlterField(
            model_name='reportecamaras',
            name='rio_pescado_descripcion',
            field=models.TextField(default='No se detectaron novedades durante el monitoreo'),
        ),
        migrations.AlterField(
            model_name='reportecamaras',
            name='trafun_descripcion',
            field=models.TextField(default='No se detectaron novedades durante el monitoreo'),
        ),
    ]
